Add yearly summary table for licenses page
IsThereAnyDeal/AugmentedSteam pull request #1723
Opened 2023-08-09 02:41 UTC by L1Q

Do you ever wonder how many games you bought in a certain year as opposed to just claiming them for free?
Or how many games you were gifted in total? All the data is there, you just need to crunch some numbers, now automated!

Applies to [Home > Account > Licenses and product key activations](https://store.steampowered.com/account/licenses/)

Adds a summary table of games added to the account per year per category.

![image](https://github.com/IsThereAnyDeal/AugmentedSteam/assets/6942070/6a25ee43-99d1-43e0-9f42-d443245d8de2)

Tested in Chrome.
Fully translated using existing Localization lines.

2023-09-11 11:17 UTC, MxtOUT requested changes

2023-09-11 19:47 UTC, L1Q commented on src/js/Content/Features/Store/Licenses/FLincensesSummary.js
> +            const year = item.querySelector( ".license_date_col" ).innerHTML.split( " " )[2];
Fixed, tested on every language Steam currently has. They put the either either in the end or the beginning of the line, always four digits. In this assumption is going to fail, the page will still look correct.

Also fixed the feature not running on the page with ``/?l=`` parameters.

2023-09-12 09:06 UTC, MxtOUT commented
This looks good, thanks!
I merged the two regexes into one, so if you could confirm my changes one last time, that would be very appreciated!

2023-09-12 09:18 UTC, L1Q commented
Thank you so much! It looks correct in every langugage.
![chrome_ClTsU3PWk8](https://github.com/IsThereAnyDeal/AugmentedSteam/assets/6942070/9597be08-e30d-489a-aae9-1c7105e2a4fd)

2023-09-12 09:20 UTC, merged